# Configuración para el perfil de desarrollo (dev)
Comentario:
  property: Comentario Profile Prod  # Propiedad personalizada para el perfil prod

# Puerto para el entorno de producción
server:
  port: 0  # Asigna un puerto dinámico

spring:
  application:
    name: api-rest-mongo  # Nombre del servicio para producción
  data:
    mongodb:
      uri: mongodb://prod-mongo-host:27017/tienda_db  # Base de datos de producción en un servidor MongoDB remoto

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Asegúrate de que este sea el URL correcto de tu Eureka Server en producción
  instance:
    prefer-ip-address: true
    metadata-map:
      port: ${server.port}  # El puerto asignado dinámicamente
    instance-id: ${spring.application.name}:${server.port}:${random.value}  # ID de la instancia
app:

  test-prop: "tercer valor que se envia desde Config Server "
